#!/bin/bash

source /winattacklab/.deploy
source /winattacklab/.destroy
cd /winattacklab/

case "$DEPLOYED" in
        init)
            echo "`date`: terraform deplyoment not yet startet"
			echo "`date`: if you want to start deploying, click on the \"Run Task\" button"
            ;;

        deploying)
            ps -ef|grep "/usr/bin/terraform apply" | grep -v grep > /dev/null
            RESULT=$?
            if [ $RESULT -eq 0 ]; then
                echo "`date`: terraform deployment is still running" >> /winattacklab/logs/terraform-apply.log
            else
                echo "`date`: terraform apply has finished" >> /winattacklab/logs/terraform-apply.log
                echo "DEPLOYED=\"finished\"" > /winattacklab/.deploy
            fi

			echo "`date`: opening deployment log"
            sleep 5
            tail -n +0 -f /winattacklab/logs/terraform-apply.log
            ;;

        finished)
		    echo "`date`: terraform deployment has been finished"
			echo "`date`: opening deployment log"
            sleep 5
            cat /winattacklab/logs/terraform-apply.log
            ;;

        *)
            exit 1

esac






