#!/bin/bash
echo "========================================"
echo "destroy script"
echo "========================================"
for ((COUNT = 2; COUNT <= 12; COUNT++)); do
  echo "DESTROY" $COUNT
  sleep 1
done
