#!/bin/bash

if [ -e /terraform/no-content ]; then
    echo "=========================="
    echo "executing /opt/scripts/ipaddresses-task"
    echo "No content found."
    exit 0
fi

source /terraform/.deploy
source /terraform/.destroy
source /terraform/proxy.env

cd /terraform/

resource_group_name=`grep -re "^resource \"azurerm_resource_group\"" *.tf | awk -F"\"" '{print $4}'`
if [ $? -eq 0 ]; then
    echo "$(date): Resource group variable name is '$resource_group_name'." >> /terraform/logs/terraform-ipaddresses.log
else
    echo "$(date): Unable to determine resource group variable name" >> /terraform/logs/terraform-ipaddresses.log
    echo "$(date): Unable to determine resource group variable name"
fi

case "$DEPLOYED" in
init)
    echo "$(date): terraform deploy not yet started" >>/terraform/logs/terraform-ipaddresses.log
    echo "$(date): terraform deploy not yet started"
    echo "$(date): if you want to deploy, click on \"Run Task\" in the Deploy menu"
    ;;

deploying)
    ps -ef | grep "/usr/bin/terraform apply" | grep -v grep >/dev/null
    RESULT=$?
    if [ $RESULT -eq 0 ]; then
        echo "$(date): terraform apply is running" >>/terraform/logs/terraform-ipaddresses.log
        echo "$(date): terraform apply is running"
        echo "$(date): please wait until the infrastructure is fully deployed"
    else
        echo "$(date): terraform apply not running - deployment should have been finished - let's check ..." >>/terraform/logs/terraform-ipaddresses.log
        echo "$(date): terraform apply not running - deployment should have been finished - let's check ..."

        terraform state show "azurerm_resource_group.$resource_group_name" >>/terraform/logs/terraform-ipaddresses.log
        R1=$?
        if [ $R1 -eq 0 ]; then
            echo "$(date): deploy was successful: infrastructure running" >>/terraform/logs/terraform-ipaddresses.log
            echo "$(date): deploy was successful: infrastructure running"
            echo "DEPLOYED=\"finished\"" >/terraform/.deploy
            terraform output -no-color 2>&1 | tee -a /terraform/logs/terraform-ipaddresses.log

            if [ -e /terraform/terraform.end ]; then
                /opt/scripts/show-when-cron-will-destroy-infrastructure
            fi

            if [ -e /opt/scripts/show-credentials.sh ]; then
                /opt/scripts/show-credentials.sh
            fi

        else

            echo "$(date): deploy error: infrastructure not running" >>/terraform/logs/terraform-ipaddresses.log
            echo "$(date): deploy error: infrastructure not running"
        fi

    fi

    ;;

finished)
    case "$DESTROYED" in
    init)
        echo "$(date): terraform is fully deployed" >>/terraform/logs/terraform-ipaddresses.log
        echo "$(date): terraform is fully deployed"
        echo "$(date): user did not click on destroy" >>/terraform/logs/terraform-ipaddresses.log
        echo "$(date): user did not click on destroy"
        echo "====== Azure Resource Group ====="
        terraform state show "azurerm_resource_group.$resource_group_name" | grep id | cut -d'/' -f5- | cut -d '"' -f1
        echo "================================="

        terraform output -no-color 2>&1 | tee -a /terraform/logs/terraform-ipaddresses.log

        if [ -e /terraform/terraform.end ]; then
            /opt/scripts/show-when-cron-will-destroy-infrastructure
        fi

        if [ -e /opt/scripts/show-credentials.sh ]; then
            /opt/scripts/show-credentials.sh
        fi

        ;;
    running)
        ps -ef | grep "/usr/bin/terraform destroy" | grep -v grep >/dev/null
        RESULT=$?
        if [ $RESULT -eq 0 ]; then
            echo "$(date): user clicked on the destroy button" >>/terraform/logs/terraform-ipaddresses.log
            echo "$(date): user clicked on the destroy button"
            echo "$(date): terraform destroy has started" >>/terraform/logs/terraform-ipaddresses.log
            echo "$(date): terraform destroy has started"
        else
            echo "$(date): user clicked on the destroy button" >>/terraform/logs/terraform-ipaddresses.log
            echo "$(date): user clicked on the destroy button"

            terraform state show "azurerm_resource_group.$resource_group_name" >>/terraform/logs/terraform-ipaddresses.log
            R1=$?
            if [ $R1 -eq 0 ]; then
                echo "$(date): destroy not finished yet: infrastructure still running" >>/terraform/logs/terraform-ipaddresses.log
                echo "$(date): destroy not finished yet: infrastructure still running"
            else
                echo "$(date): infrastructure is fully down" >>/terraform/logs/terraform-ipaddresses.log
                echo "$(date): infrastructure is fully down"
                echo "DESTROYED=\"finished\"" >/terraform/.destroy
                echo "DEPLOYED=\"init\"" >/terraform/.deploy
            fi

        fi
        ;;

    finished)
        echo "$(date): destroy successfully finished - will reset deployment to init" >>/terraform/logs/terraform-ipaddresses.log
        echo "$(date): destroy successfully finished - will reset deployment to init"
        echo "DEPLOYED=\"init\"" >/terraform/.deploy
        echo "DESTROYED=\"init\"" >/terraform/.destroy
        ;;
    *)
        exit 1
        ;;
    esac
    ;;

*)
    exit 1
    ;;

esac
