#!/bin/bash
echo "========================================"
echo "log script"
echo "========================================"
for ((COUNT = 6; COUNT <= 16; COUNT++)); do
  echo "LOG" $COUNT
  sleep 1
done
