#!/bin/bash

source /winattacklab/.deploy
source /winattacklab/.destroy
cd /winattacklab

echo "`date`: terraform log"

echo "====== terraform state list ====="
terraform state list -no-color

echo "====== terraform log ====="
terraform output -no-color

echo "====== terraform version ====="
terraform version -no-color

echo "====== history  ====="
tail -n +0 -f /winattacklab/logs/terraform-status.log
