#!/bin/bash

echo "`date`: cronjob run" >> /tmp/cron.log

if [ -e /winattacklab/terraform.end ]; then
  START=$(cat "/winattacklab/terraform.start")
  END=$(cat "/winattacklab/terraform.end")
  NOW=$(date +%s);

  if [ $((END-NOW)) -gt 0 ]; then
    echo "`date`: will not destroy deployment" >> /tmp/terraform15min.bot
    echo "`date`: auto destroyment will run after `date -d @$((END))`" >> /tmp/terraform15min.bot
    echo "`date`: auto destroyment will run in $((END-NOW)) seconds" >> /tmp/terraform15min.bot
    echo "`date`: auto destroyment will run in $((END-NOW)) seconds" >> /tmp/cron.log
  else
    echo "`date`: auto destroyment will should have been run on `date -d @$((END))`" >> /tmp/terraform15min.bot
    echo "`date`: terraform deployment expired - will destroy now" >> /tmp/terraform.destroy
    echo "`date`: auto destroyment will run in $((END-NOW)) seconds" >> /tmp/cron.log
    rm /winattacklab/terraform.start
    rm /winattacklab/terraform.end
    cd /winattacklab

    echo "DESTROYED=\"running\"" > /winattacklab/.destroy
    echo "terraform destroy --auto-approve" >> /tmp/terraform.destroy
    echo "`date`: automatic terraform destroy --auto-approve started" >> /winattacklab/logs/terraform-status.log
    echo "`date`: automatic terraform destroy log" >> /winattacklab/logs/terraform-destroy.log
    echo "`date`: destroy executed by cron" >> /terraform.destroy.cron
    terraform destroy -no-color --auto-approve 2>&1 | egrep -v '\$PlainPassword =|\$labdcadminpw =|\$password =' >> /tmp/terraform15min.bot.destroy
    echo "`date`: terraform destroy --auto-approve finished" >> /winattacklab/logs/terraform-status.log
  fi
else
  echo "`date`: do nothing: currently nothing deployed" >> /tmp/terraform15min.bot.destroy
  echo "`date`: do nothing: currently nothing deployed" >> /tmp/cron.log
fi


if [ -e /tmp/terraform.destroy.cron ]; then
  ps -ef|grep "/usr/bin/terraform destroy"|grep -v grep > /dev/null
  RESULT=$?
  if [ $RESULT -eq 0 ]; then
      echo "`date`: terraform destroy is still running" >> /tmp/terraform15min.bot
      echo "`date`: terraform destroy is still running" >> /tmp/cron.log
  else
      echo "`date`: terraform destroyment currently not running" >> /tmp/terraform15min.bot
      echo "`date`: terraform destroyment currently not running" >> /tmp/cron.log
      cd /winattacklab/
      terraform state show 'azurerm_resource_group.winattacklabgroup' >> /tmp/terraform15min.bot
      R1=$?
      if [ $R1 -eq 0 ]; then
          echo "`date`: destroy was not yet successul: infrastructure still running" >> /tmp/terraform15min.bot
          echo "`date`: destroy was not yet successul: infrastructure still running" >> /tmp/cron.log
          echo "`date`: running terraform destry again" >> /tmp/terraform15min.bot
          cd /winattacklab/
          terraform destroy -no-color --auto-approve 2>&1 | egrep -v '\$PlainPassword =|\$labdcadminpw =|\$password =' >> /tmp/terraform15min.bot.destroy
      else
          echo "`date`: infrastructure is fully down" >> /tmp/terraform15min.bot
          echo "`date`: infrastructure is fully down" >> /tmp/cron.log
          echo "`date`: will set .destroy and .deploy to init and remove /tmp/terraform.destroy.cron" >> /tmp/terraform15min.bot
          echo "DESTROYED=\"init\"" > /winattacklab/.destroy
          echo "DEPLOYED=\"init\"" > /winattacklab/.deploy
	  cat /tmp/terraform.destroy.cron >> /tmp/terraform.destroy.cron.history
 	  rm /tmp/terraform.destroy.cron
      fi    
  fi
fi


