#!/bin/bash

if [ -e /winattacklab/terraform.end ]; then
  START=$(cat "/winattacklab/terraform.start")
  END=$(cat "/winattacklab/terraform.end")
  NOW=$(date +%s);

  if [ $((END-NOW)) -gt 0 ]; then
    echo "`date`: nothing to do" >> /tmp/terraform.bot
    echo "`date`: auto destroyment will run on `date -d @$((END))`" >> /tmp/terraform.bot
    echo "`date`: auto destroyment will run in $((END-NOW)) seconds" >> /tmp/terraform.bot
  else
    echo "`date`: terraform deployment expired - will destroy now" > /tmp/terraform.destroy
    mv /winattacklab/terraform.start /winattacklab/terraform.start.bak
    mv /winattacklab/terraform.end /winattacklab/terraform.end.bak
    cd /winattacklab

    echo "DESTROYED=\"running\"" > /winattacklab/.destroy
    echo "terraform destroy --auto-approve" >> /tmp/terraform.destroy
    echo "`date`: automatic terraform destroy --auto-approve started" >> /winattacklab/logs/terraform-status.log
    echo "`date`: automatic terraform destroy log" > /winattacklab/logs/terraform-destroy.log
    echo "true" > /tmp/terraform.init
    terraform destroy -no-color --auto-approve 2>&1 | egrep -v '\$PlainPassword =|\$labdcadminpw =|\$password =' >> /tmp/terraform.bot.destroy
    echo "`date`: terraform destroy --auto-approve finished" >> /winattacklab/logs/terraform-status.log

  fi
else
  echo "`date`: do nothing: file /winattacklab/terraform.end not found" >> /tmp/terraform.bot.destroy
fi


if [ -e /winattacklab/terraform.init ]; then
  ps -ef|grep "/usr/bin/terraform destroy"|grep -v grep > /dev/null
  RESULT=$?
  if [ $RESULT -eq 0 ]; then
      echo "`date`: terraform destroyment is still running" >> /tmp/terraform.bot
  else
      echo "`date`: terraform destroy has finished" >> /tmp/terraform.bot
      echo "DESTROYED=\"init\"" > /winattacklab/.destroy
      echo "DESTROYED=\"init\"" > /winattacklab/.deploy
      rm /tmp/terraform.init
      rm /tmp/terraform.bot.destroy
  fi
fi


