#!/usr/bin/with-contenv bash

cd /winattacklab

# SETUP EMPTY LOGS
touch /winattacklab/terraform-plan.log
touch /winattacklab/logs/terraform-apply.log
touch /winattacklab/logs/terraform-destroy.log
touch /winattacklab/logs/terraform-ipaddresses.log
touch /winattacklab/logs/terraform-status.log
touch /winattacklab/logs/terraform-init.log

# SETUP DATE
mydate=`date +%Y-%m-%d--%H-%M-%S`
sed -i -e "s/E1DATE/$mydate/g" main.tf

# SETUP ACCOUNT
myusername="lab_admin"
mypassword=`pwgen 10 1 -c 1 -n 1`

sed -e "s/LAB_ADMIN/$myusername/g" /winattacklab/terraform.tfvars > /winattacklab/terraform.tfvars.neu
sed -e "s/LAB_PASSWORD/$mypassword/g" /winattacklab/terraform.tfvars.neu > /winattacklab/terraform.tfvars

sed -i -e "s/LAB_ADMIN/$myusername/g" /opt/scripts/ipaddresses-task
sed -i -e "s/LAB_PASSWORD/$mypassword/g" /opt/scripts/ipaddresses-task

echo "Username: $myusername" > /tmp/credentials.txt
echo "Password: $mypassword" >> /tmp/credentials.txt
echo "===" >> /tmp/credentials.txt

# INIT
terraform init -no-color 2>&1 > /winattacklab/logs/terraform-init.log
echo "`date`: terraform init executed" >> /winattacklab/logs/terraform-status.log

# CREATE PLAN
terraform plan -no-color -out /winattacklab/terraform-plan 2>&1 > /winattacklab/terraform-plan.log
echo "`date`: terraform plan executed" >> /winattacklab/logs/terraform-status.log

