#!/usr/bin/with-contenv bash

touch /winattacklab/logs/az.log

# Attempt to log in to Azure
echo "`date`: Attempting to log in to Azure" >> /winattacklab/logs/az.log

client_id=`grep '^client_id' /winattacklab/terraform.tfvars | grep  -o '"[0-9a-z\-]*"' | cut -d '"' -f2`
client_secret=`grep '^client_secret' /winattacklab/terraform.tfvars | grep  -o '".*"' | cut -d '"' -f2`
tenant_id=`grep '^tenant_id' /winattacklab/terraform.tfvars | grep  -o '"[0-9a-z\-]*"' | cut -d '"' -f2`

az login --service-principal -u $client_id -p $client_secret --tenant $tenant_id >> /winattacklab/logs/az.log 2>&1
if [ $? -eq 0 ]; then
    echo "az_available=true" > /winattacklab/az_login
    echo "`date`: Azure login available." | tee -a /winattacklab/logs/az.log
else
    echo "az_available=false" > /winattacklab/az_login
    echo "`date`: Azure login NOT available." | tee -a /winattacklab/logs/az.log
    exit 1
fi
